apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrms-backend
  namespace: hrms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hrms-backend
  template:
    metadata:
      labels:
        app: hrms-backend
    spec:

      initContainers:
        - name: wait-for-mysql
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z mysql 3306; do
                echo "Waiting for MySQL..."
                sleep 2
              done

      containers:
        - name: backend
          image: ghandgevikas/hrms-backend:v1.1
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
            - name: DB_HOST
              value: "mysql"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "root"
            - name: DB_NAME
              value: "hrms"
