apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: hrms
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - port: 5003
      targetPort: 5003
