apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-service
  namespace: hrms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qr-service
  template:
    metadata:
      labels:
        app: qr-service
    spec:
      containers:
        - name: qr-service
          image: ghandgevikas/hrms-qr-service:latest
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
